x-env-args: &env-args
  DOCKER_BUILDKIT: 1
  NODE_ENV: docker
  SERVICE: api
  SHELL: /bin/sh

services:
  api:
    build:
      context: ../../
      dockerfile: ./scripts/services/docker/Dockerfile.backend
    command: 'npm run start:api'
    working_dir: /usr/gitmesh/app/backend
    env_file:
      - ../../backend/.env.dist.local
      - ../../backend/.env.dist.composed
      - ../../backend/.env.override.local
      - ../../backend/.env.override.composed
    environment:
      <<: *env-args
      CREWAI_SERVICE_URL: http://chat-orchestrator:8001
      CREWAI_SERVICE_TOKEN: ${CREWAI_SERVICE_TOKEN:-dev-token}
    ports:
      - '8080:8080'
    restart: always
    networks:
      - gitmesh-bridge

  api-dev:
    build:
      context: ../../
      dockerfile: ./scripts/services/docker/Dockerfile.backend
    command: 'npm run start:api:dev'
    working_dir: /usr/gitmesh/app/backend
    # user: '${USER_ID}:${GROUP_ID}'
    env_file:
      - ../../backend/.env.dist.local
      - ../../backend/.env.dist.composed
      - ../../backend/.env.override.local
      - ../../backend/.env.override.composed
    environment:
      <<: *env-args
      CREWAI_SERVICE_URL: http://chat-orchestrator-dev:8001
      CREWAI_SERVICE_TOKEN: ${CREWAI_SERVICE_TOKEN:-dev-token}
      NODE_PATH: /usr/gitmesh/app/backend/node_modules:/usr/gitmesh/app/services/libs/integrations/node_modules
    hostname: api
    ports:
      - '8080:8080'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - gitmesh-bridge
    volumes:
      - ../../services/libs/alerting/src:/usr/gitmesh/app/services/libs/alerting/src:z
      - ../../services/libs/common/src:/usr/gitmesh/app/services/libs/common/src:z
      - ../../services/libs/conversations/src:/usr/gitmesh/app/services/libs/conversations/src:z
      - ../../services/libs/cubejs/src:/usr/gitmesh/app/services/libs/cubejs/src:z
      - ../../services/libs/database/src:/usr/gitmesh/app/services/libs/database/src:z
      - ../../services/libs/feature-flags/src:/usr/gitmesh/app/services/libs/feature-flags/src:z
      - ../../services/libs/integrations/src:/usr/gitmesh/app/services/libs/integrations/src:z
      - ../../services/libs/ioc/src:/usr/gitmesh/app/services/libs/ioc/src:z
      - ../../services/libs/logging/src:/usr/gitmesh/app/services/libs/logging/src:z
      - ../../services/libs/opensearch/src:/usr/gitmesh/app/services/libs/opensearch/src:z
      - ../../services/libs/redis/src:/usr/gitmesh/app/services/libs/redis/src:z
      - ../../services/libs/sentiment/src:/usr/gitmesh/app/services/libs/sentiment/src:z
      - ../../services/libs/sqs/src:/usr/gitmesh/app/services/libs/sqs/src:z
      - ../../services/libs/temporal/src:/usr/gitmesh/app/services/libs/temporal/src:z
      - ../../services/libs/tracing/src:/usr/gitmesh/app/services/libs/tracing/src:z
      - ../../services/libs/types/src:/usr/gitmesh/app/services/libs/types/src:z
      - ../../backend/src:/usr/gitmesh/app/backend/src:z
      - ../../backend/package.json:/usr/gitmesh/app/backend/package.json:z
      - ../../../premium-backend/src/services/premium:/usr/gitmesh/app/backend/src/services/premium:z
      - ../../../premium-backend/src/api/premium:/usr/gitmesh/app/backend/src/api/premium:z
      - ../../../premium-libs/src/integrations/premium:/usr/gitmesh/app/services/libs/integrations/src/integrations/premium:z
      - ../../services/libs/integrations/src/integrations/nango:/usr/gitmesh/premium-libs/src/integrations/nango:z
      - /usr/gitmesh/app/backend/node_modules

networks:
  gitmesh-bridge:
    external: true
